#services:
#  db:
#    image: mysql:8
#    container_name: mysql_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: upstox_db
#      MYSQL_USER: upstox_user
#      MYSQL_PASSWORD: upstox_pass
#    ports:
#      - "3307:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#  app:
#    build: .
#    container_name: upstox_app
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./.env
#
#volumes:
#  db_data:
#
services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mohandb
      MYSQL_DATABASE: trading_db
      MYSQL_USER: mohanspring
      MYSQL_PASSWORD: mohandb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: upstox_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  db_data:


